server:
  port: 8080

spring:
  application:
    name: globaldocs-solutions
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

logging:
  level:
    com.globaldocs: INFO
